### ISSUE TITLE
Only works with English

### ISSUE THREAD

**Issue by maiconzucco** [tleish/redmine_editor_preview_tab#1]
Hi,

First, congratulations for the plugin. Is very useful.
But, It works only if the user language is English.

Can you fix it?

Thanks

**Comment by tleish** [comment]
What language are you interested in?

**Comment by tleish** [comment]
Just commited a fix that I believe should now support other languages.

To get full support so all labels of plugin are supported, 2 strings from that language need to be translated.

See config/locals/en.yml

``` yaml
en:
  label_no_preview: Nothing to preview
  label_write: Write
```
